import { Cinzel, Cinzel_Decorative } from "next/font/google";
import "./globals.css";
//import Header from "../components/Header";
const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
  weight: "400",
});

const cinzel_d = Cinzel_Decorative({
  variable: "--font-cinzel_d",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "UniNav",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${cinzel_d.variable} antialiased`}
      >
        {/*<Header/>*/}
        {children}
      </body>
    </html>
  );
}
